default:
    hes_data_url: "https://files.digital.nhs.uk/assets/Services/Artificial%20data/Artificial%20HES%20final/"
    hes_data_file_name: "artificial_hes_ae_202302_v1_sample.zip"
    download_destination: "data_in/"
    downloaded_hes_folder: "data_in/artificial_hes_ae_202302_v1_sample/"
    downloaded_hes_file: "artificial_hes_ae_2122.csv"
    output_path: "data_out/"
  
dev:
    test: "dev"